version: '3'
services:
  database:
    image: postgres:15.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Enikson@1
      POSTGRES_USER: root
      POSTGRES_DB: server-blog-api
      
    ports:
      - 5432:5432